name: Security Gate Class SCA

on: push

jobs:
  scan_security:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o codigo do repositorio
        uses: action/checkout@v4

      - name: Scanner de Vulnerabilidades (Bloqueia CRITICAS)
        uses: aquasecurity/trivy-actions@master
        with:
          scan-type: 'fs'
          formal: 'table'
          severity: 'HIGH.CRITICAL'
          exit-code: '1'